### ISSUE TITLE
Custom message not returned to Meteor.call error parameter

### ISSUE THREAD

**Issue by wildhart** [Zodiase/meteor-check#2]
Hi Zodiase.  This package is just what I'm looking for, thanks.  However, the custom error message is not being returned from within a method.

I want to return custom messages to a form validator where the validation has to happen within `Meteor.call('foo', test, function (error, result) {} )` because it has to happen on the server.  Maybe I'm using it wrong:

On the client (user is requesting a new account, subdomain.myapp.com):

```
Meteor.call('companySettings.checkAvailable', domain, function(err, response) {
        if (err) console.log(err, response);
        ...      
});
```

On the server:

```
Match.subdomain = Match.Where(function (x) {
  return new RegExp(/^[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?$/).test(x);
});

Meteor.methods({
    "companySettings.checkAvailable": function(domain) {
        /************************** VALIDATE INPUTS ****************************************/
        check(domain, Match.subdomain, "Invalid domain");
        ...
```

But my custom message is not returned.  In the console for an invalid domain:

```
trial.js:14:
errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}
```

If I do it directly in the console then it works:

```
try{check("asdf.", Match.subdomain, "Invalid domain");} catch(err){console.log("message:",err)}
message: Error: Invalid domain(…)
```

Am I doing something wrong?

Cheers

**Comment by wildhart** [comment]
Sorry, this is a duplicate of #1 - I didn't see that, thought mine was the first issue.

So it looks like your package will not help my use case.  I'll have to resort to `Try {check...} catch(err) {Throw new Meteor.Error(500,'Invalid domain').`

**Comment by Zodiase** [comment]
@wildhart Yeah I hope you could understand that I don't want to compromise the original behavior of `check`. Using `check` for input checks for Meteor calls is very common even in my projects but it is not the entire usage of `check`. Often times I may just want to hint users of a certain package that they are providing incorrect parameters. Propagating such errors to the client side would be an undesirable side-effect.

In your specific case though, although not exactly the way you want it, using this package can still simplify your code a bit.

I'll just explain by this example:

``` JavaScript
// Previously:
someMethod (popularity, domain) {
    try {
        check(popularity, Number);
    } catch (err) {
        throw new Meteor.Error('Invalid popularity. Expecting a number.');
    }

    try {
        check(domain, RegEx_validDomain);
    } catch (err) {
        throw new Meteor.Error('Invalid domain.');
    }

    // Could be worse if there were more to check.
}


// Now:
someMethod (popularity, domain) {
    // Expose errors in this section to client.
    try {
        check(popularity, Number, 'Invalid popularity. Expecting a number.');
        check(domain, RegEx_validDomain, 'Invalid domain.');

        // Any more checks to perform.
    } catch (err) {
        throw new Meteor.Error('Invalid Input', err.message);
    }

    // Do other stuff and throw errors that are hidden from client.
}


// May also create a helper function for the wrapping for better V8 optimization. (See https://github.com/petkaantonov/bluebird/wiki/Optimization-killers)

throwMeteorError (errorType, callback) {
    try {
        callback();
    } catch (err) {
        throw new Meteor.Error(errorType, err.message);
    }
}

someMethod (popularity, domain) {
    // Expose errors in this section to client.
    throwMeteorError('Invalid Input', () => {
        check(popularity, Number, 'Invalid popularity. Expecting a number.');
        check(domain, RegEx_validDomain, 'Invalid domain.');

        // Any more checks to perform.
    });

    // Do other stuff and throw errors that are hidden from client.
}
```

**Comment by wildhart** [comment]
Thanks @Zodiase, I've done something very similar.

It might be worth mentioning in the README.md that your package isn't intended to transmit custom validation messages from server to client (and why) - both myself and @lyquocnam from #1 assumed that it would.

**Comment by Zodiase** [comment]
@wildhart Sure I'll remember to add that. Thanks for the note. Also I've updated my last comment to add an improved example, in case it might help you.

**Comment by wildhart** [comment]
Just seen your edit.  What I've done is to reproduce your entire code but using `throw new Meteor.Error` instead of `Match.error`.  I know that if I supply a custom message then it is safe to expose to the client.  If  I don't want to expose the message I omit it.

My I suggest you add this as an option in your package - allow a 4th parameter:
`check = function (value, pattern, message, expose)`

Then if expose is set to true your code uses Meteor.Error, if false or undefined you use Match.Error.  That way the user has to knowingly set it true and will understand the implications.
